language: bash
services: docker

env:
  - VERSION=5.5
  - VERSION=5.6
  - VERSION=7.0
  - VERSION=7.1
  - VERSION=7.2

before_script:
  - cd "$VERSION"
  - IMAGE="104corp/php-testing"
  - IMAGE_VERSION="${VERSION}${VARIANT:+-$VARIANT}"
  - IMAGE_VERSION="${IMAGE_VERSION//'/'/-}"
  - IMAGE_NAME="$IMAGE:$IMAGE_VERSION"
  - echo "$IMAGE_NAME"

script:
  - docker build -t "$IMAGE_NAME" "${VARIANT:-.}"
  - docker images

after_success:
  - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
  - docker push $IMAGE
