name: Publish Docker

on: [push]

jobs:
  alpine:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["7.3", "7.2", "7.1", "7.0", "5.6", "5.5"]
    steps:
      - uses: actions/checkout@master
      - name: Build PHP ${{ matrix.version }} and publish to GitHub Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: 104corp/docker-php-testing/alpine:${{ matrix.version }}
          username: ${{ secrets.GITHUB_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: ${{ matrix.version }}/Dockerfile

  apache:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["7.3", "7.2", "7.1", "7.0", "5.6", "5.5"]
    steps:
      - uses: actions/checkout@master
      - name: Build PHP ${{ matrix.version }} and publish to GitHub Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: 104corp/docker-php-testing/apache:${{ matrix.version }}
          username: ${{ secrets.GITHUB_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: ${{ matrix.version }}/apache/Dockerfile
