name: Testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: PHP testing actions
        uses: 104corp/docker-php-testing@master
        with:
          args: php -v && php -m
